# BINARIES := cf-of cf of
# include ../../utils/Makefile.multiple

PROGNAME := cf
include ../../utils/Makefile.single

# PROGNAME := of
# include ../../utils/Makefile.generic

# PROGNAME := cf-of
# include ../../utils/Makefile.generic
